# Generated by Django 2.0 on 2021-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loginlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('login_time', models.DateTimeField()),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('img1', models.IntegerField()),
                ('img2', models.IntegerField()),
                ('result', models.IntegerField()),
                ('operation', models.IntegerField()),
                ('operation_scroll', models.IntegerField()),
                ('op_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('check_list', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
