# Generated by Django 2.0 on 2021-04-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210402_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
