# Generated by Django 2.0 on 2021-04-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
