# Generated by Django 2.0 on 2021-05-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210510_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='img_num1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='img_num2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
