# Generated by Django 2.0 on 2021-05-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='img1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='img2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
