# Generated by Django 2.0 on 2021-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='collections',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='devices',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='time_plan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
